### GET Request get app products ###

GET http://localhost:3000/products
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODBjMDA1MDY2N2VkN2RiM2VkMzZjMCIsImlhdCI6MTY4NjE1OTM4NX0.ulOkDiKB7fHOwojMUQVODwOVQJxF8_Zqlt8xqAhz5dY

### POST Request add products ###

POST http://localhost:3000/products
Content-Type: application/json
Accept: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODBjMDA1MDY2N2VkN2RiM2VkMzZjMCIsImlhdCI6MTY4NjE1OTM4NX0.ulOkDiKB7fHOwojMUQVODwOVQJxF8_Zqlt8xqAhz5dY

{
  "name": "Product 3",
  "price": 10
}


### POST Request get products by ids ###

POST http://localhost:3000/products/search
Content-Type: application/json
Accept: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODBjMDA1MDY2N2VkN2RiM2VkMzZjMCIsImlhdCI6MTY4NjE1OTM4NX0.ulOkDiKB7fHOwojMUQVODwOVQJxF8_Zqlt8xqAhz5dY

{
  "ids":["6480c03c796ffcf65a74cadf","6480c045796ffcf65a74cae1"]
}

### !!
### GET Request get all orders ###

GET http://localhost:3001/orders
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODBjMDA1MDY2N2VkN2RiM2VkMzZjMCIsImlhdCI6MTY4NjE1OTM4NX0.ulOkDiKB7fHOwojMUQVODwOVQJxF8_Zqlt8xqAhz5dY

### POST Request add order ###

POST http://localhost:3001/orders
Content-Type: application/json
Accept: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODBjMDA1MDY2N2VkN2RiM2VkMzZjMCIsImlhdCI6MTY4NjE1OTM4NX0.ulOkDiKB7fHOwojMUQVODwOVQJxF8_Zqlt8xqAhz5dY

{
  "ids":["6480c03c796ffcf65a74cadf","6480c045796ffcf65a74cae1"]
}



## !! auth
### POST login ###

POST http://localhost:3002/api/v1/login
Content-Type: application/json
Accept: application/json

{
  "email":"ayadi@gmail.com",
  "password":"ayadi123"
}

### POST register ###

POST http://localhost:3002/api/v1/register
Content-Type: application/json
Accept: application/json

{
  "email":"ayadi@gmail.com",
  "password":"ayadi123",
  "name":"ayadi oussama"
}


### GET  verify if user is auth

GET http://localhost:3002/api/v1/verify
Content-Type: application/json
Accept: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODBjMDA1MDY2N2VkN2RiM2VkMzZjMCIsImlhdCI6MTY4NjE1OTM4NX0.ulOkDiKB7fHOwojMUQVODwOVQJxF8_Zqlt8xqAhz5dY
